name: Build Android APK

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - uses: android-actions/setup-android@v3

      - name: Install deps
        run: npm ci

      - name: Remove server config for production build
        run: |
          sed -i '/server:/,/},/d' capacitor.config.ts

      - name: Build web
        run: npm run build

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Build debug APK
        run: cd android && ./gradlew :app:assembleDebug

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk

      - name: Create GitHub Release with APK
        uses: softprops/action-gh-release@v2
        with:
          tag_name: apk-debug-${{ github.run_number }}
          name: Debug APK ${{ github.run_number }}
          prerelease: true
          files: |
            android/app/build/outputs/apk/debug/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
